name: template_flutter
description: "A new Template Flutter."

publish_to: '1.0.0.0' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.1
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  provider: ^6.1.2
  intl: ^0.19.0
  uuid: ^4.4.0
  hive: ^2.2.3
  http: ^1.2.2
  gal: ^2.3.0
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon.png"
  image_path_android: "assets/icons/icon.png"
  min_sdk_android: 21
  background_color: "#FFFFFF"
  theme_color: "#FFFFFF"

  ios: true
  image_path_ios: "assets/icons/icon.png"
  remove_alpha_channel_ios: true

  web:
    generate: true
    image_path: "assets/icons/icon.png"

  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/icons/icon.png"
